BaillyThibaut/MVC/Controllers/AbsenceController.cs
using BusinessManager;
using Model.Entities;
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class AbsenceController : Controller
    {
        // GET: Absence
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(AbsenceVM model, int eleveId = -1)
        {
            if (eleveId == -1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                Absence absence = new Absence() { Motif = model.Motif, DateAbsence = model.DateAbsence, EleveId = eleveId };
                Manager.Instance.AddAbsence(absence);
                return RedirectToAction("Detail", "Eleve", new { id = absence.EleveId });
            }
            return View(model);
        }
    }
}

BaillyThibaut/MVC/Controllers/EleveController.cs
using BusinessManager;
using Model.Entities;
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class EleveController : Controller
    {
        // GET: Eleve
        public ActionResult EleveList(string recherche)
        {
            List<Eleve> eleves = Manager.Instance.GetAllEleve();
            List<EleveVM> eleveVMs = new List<EleveVM>();
            if (eleves != null)
            {
                foreach (Eleve e in eleves)
                {
                    eleveVMs.Add(new EleveVM(e));
                }
            }
            if (recherche != null)
            {
                eleveVMs = eleveVMs.Where(eleve => eleve.Nom.ToLower().Contains(recherche.ToLower()) || eleve.Prenom.ToLower().Contains(recherche.ToLower())).ToList();
            }
            
            return View(eleveVMs);
        }

        public ActionResult Detail(int id = -1)
        {
            if (id == -1)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);

            Eleve eleve = Manager.Instance.getOneEleveById(id);

            if (eleve == null)
                return HttpNotFound();

            return View(new EleveVM(eleve));
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(EleveVM model)
        {
            if (ModelState.IsValid)
            {
                Eleve eleve = new Eleve() { Absences = model.Absences, ClasseId = model.ClasseId, DateDeNaissance = model.DateDeNaissance, Nom = model.Nom, Notes = model.Notes, Prenom = model.Prenom };
                Manager.Instance.AjouterEleve(eleve);
                return RedirectToAction("EleveList", "Eleve");
            }
            return View();
        }
    }
}

BaillyThibaut/MVC/Controllers/NoteController.cs
using BusinessManager;
using Model.Entities;
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class NoteController : Controller
    {
        public ActionResult Add()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Add(NoteVM model, int eleveId = -1)
        {
            if(eleveId == -1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                Note note = new Note() { Appreciation = model.Appreciation, DateNote = model.DateNote, EleveId = eleveId, Matiere = model.Matiere, Valeur = model.Valeur };
                Manager.Instance.AddNote(note);
                return RedirectToAction("Detail", "Eleve", new { id = note.EleveId });
            }
            return View(model);
        }
    }
}

BaillyThibaut/MVC/Views/Eleve/Add.cshtml
@model MVC.Models.EleveVM

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EleveVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDeNaissance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDeNaissance, "{0:dd/MM/yyyy}", new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.DateDeNaissance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClasseId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClasseId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClasseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "EleveList", "Eleve");
</div>

BaillyThibaut/MVC/Views/Eleve/Detail.cshtml
@using MVC.Models
@model EleveVM
@{
    ViewBag.Title = "Detail";
}

    <div>
        <div style="display: flex; justify-content: center">
            <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Id: @Model.Id</div>
                <div class="card-body">
                    <h5 class="card-title">@Model.Nom @Model.Prenom</h5>
                    <p class="card-text">@Model.DateDeNaissance</p>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="notes-etudiant" role="tabpanel">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Matière</th>
                        <th scope="col">Valeur</th>
                        <th scope="col">Date</th>
                        <th scope="col">Appréciation</th>
                        <th scope="col">Détail</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>


        </div>
        <div id="notes-etudiant" role="tabpanel">
            @Html.ActionLink("Ajouter une note", "Add", "Note", new { EleveId = @Model.Id }, new { @class = "btn btn-success" })
            <p>Moyenne : <b>@Model.Moyenne</b></p>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Matière</th>
                        <th scope="col">Valeur</th>
                        <th scope="col">Date</th>
                        <th scope="col">Appréciation</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var note in Model.Notes)
                    {
                        <tr>
                            <th scope="row">@note.Id</th>
                            <td>@note.Matiere</td>
                            <td>@note.Valeur</td>
                            <td>@note.DateNote</td>
                            <td>@note.Appreciation</td>
                        </tr>
                    }
                </tbody>
            </table>

            @if (Model.Notes.Count() == 0)
            {
                <div class="alert alert-danger" role="alert">
                    Pas de notes
                </div>
            }
        </div>
        <div id="absences-etudiant" role="tabpanel">
            @Html.ActionLink("Ajouter une absence", "Add", "Absence", new { EleveId = @Model.Id }, new { @class = "btn btn-success" })
            <p>Nombre d'absences : <b>@Model.Absences.Count()</b></p>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Motif</th>
                        <th scope="col">date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var absence in Model.Absences)
                    {
                        <tr>
                            <th scope="row">@absence.Id</th>
                            <td>@absence.Motif</td>
                            <td>@absence.DateAbsence</td>
                        </tr>
                    }
                </tbody>
            </table>

            @if (Model.Absences.Count() == 0)
            {
                <div class="alert alert-danger" role="alert">
                    <p>Pas d'absences</p>
                </div>
            }
        </div>
    </div>   

BaillyThibaut/MVC/Views/Eleve/EleveList.cshtml
@using MVC.Models
@model List<EleveVM>



    <table class="table">
        @using (Html.BeginForm())
        {
            <div class="form-row mb-2">
                @Html.TextBox("recherche", null, new { @class = "form-control", @placeholder = "Recherche"})
                <button class="btn btn-outline-success" type="submit">Rechercher</button>
            </div>
        }

        <thead>
            @Html.ActionLink("Ajouter un élève", "Add", "Eleve", null, new { @class = "btn btn-success" })
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Date de naissance</th>
                <th scope="col">Classe</th>
                <th scope="col">Details</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var eleve in Model)
            {
                <tr>
                    <th scope="row">@eleve.Id</th>
                    <td>@eleve.Nom</td>
                    <td>@eleve.Prenom</td>
                    <td>@eleve.DateDeNaissance</td>
                    <td>@eleve.ClasseId</td>
                    <td>
                        @Html.ActionLink("Détails", "Detail", "Eleve", new { id = eleve.Id }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        </tbody>
    </table>